# Generated by Django 5.2.18 on 2026-10-09 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashcollections', '0002_collectionattempt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectionattempt',
            options={'ordering': ['-attempt_date', '-created_at']},
        ),
        migrations.AlterField(
            model_name='collectionattempt',
            name='outcome',
            field=models.CharField(choices=[('COLLECTED', 'Collected'), ('PARTIAL', 'Partial Payment'), ('NOT_AVAILABLE', 'Customer Unavailable'), ('REFUSED', 'Payment Refused'), ('PROMISED', 'Promised to Pay')], max_length=20),
        ),
    ]
