# Generated by Django 5.2.18 on 2026-10-09 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashcollections', '0003_alter_collectionattempt_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='repayment',
            name='prevent_duplicate_same_day_collection',
        ),
    ]
