# Generated by Django 5.2.18 on 2026-10-08 11:37

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('reconciliation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_number', models.CharField(max_length=40, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('deposit_date', models.DateField(default=django.utils.timezone.localdate)),
                ('bank_reference', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('SUBMITTED', 'Submitted'), ('SETTLED', 'Settled'), ('MISMATCH', 'Mismatch')], default='CREATED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposits', to='core.bankaccount')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposits', to='core.branch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_deposits', to=settings.AUTH_USER_MODEL)),
                ('reconciliation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposits', to='reconciliation.reconciliation')),
            ],
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settled_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('settlement_date', models.DateTimeField(blank=True, null=True)),
                ('settlement_reference', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SETTLED', 'Settled'), ('MISMATCH', 'Mismatch'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deposit', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='settlement', to='deposits.bankdeposit')),
            ],
        ),
    ]
